repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: python -m flake8 
        language: system
        types: [python]
        exclude: 'examples'
    -   id: black
        name: black
        entry: python -m black --check
        language: system
        types: [python]
        exclude: 'examples|docs'