site_name: mkShapesRDF
nav:
  - Home: index.md
  - "Framework":
      # - 'mkShapesRDF': 'mkShapesRDF.md'
      - "shapeAnalysis":
          - "mkShapesRDF": "shape/mkShapesRDF.md"
          - "Runner": "shape/runner.md"
          - "Configuration Folder Structure": "shape/config.md"
          - "mkPlot": "shape/mkPlot.md"
          - "mkDatacards": "shape/mkDatacards.md"
      - "processor":
          - "mkPostProc": "proc/mkPostProc.md"
          - "Processor": "proc/processor.md"
          - "Steps_cfg": "proc/Steps_cfg.md"
          - "Productions_cfg": "proc/Productions_cfg.md"
          - "Samples": "proc/samples.md"
      - "lib":
          - "parseCpp": "lib/parseCpp"
          - "SearchFiles": "lib/SearchFiles"
      - "tests":
          - "parseCpp": "tests/parseCpp"
theme:
  name: readthedocs

plugins:
  - search:
      indexing: "full"
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
