name: tests
run-name: ${{ github.actor }} is running mkShapesRDF tests 🚀
on: [push]
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
            cd ${{ github.workspace }}
            ./tests/test_env.sh
      - run: echo "All done"
      - run: echo "🍏 This job's status is ${{ job.status }}."
